export default {
  NO_CHARACTER_FOUND: 'NO_CHARACTER_FOUND_ERROR',
  DUPLICATE_CHARACTER_ERROR: 'DUPLICATE_CHARACTER_ERROR',

  CHARACTER_CLAIMED_ERROR: 'CHARACTER_CLAIMED_ERROR',
  OWNER_NOT_FOUND_ERROR: 'OWNER_NOT_FOUND_ERROR',
};
